services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: python_api
    container_name: DuyLongAPI
    depends_on: 
      - database
    volumes:
      - ../python_api:/app/python_api  # Mount the local python_api directory
      - ~/.ssh:/root/.ssh:ro  # Optional: Mount SSH keys if needed for git operations
    ports:
      - 3346:3346 # Expose port for API access
    working_dir: /app/python_api
    tty: true  # Keep container running
    stdin_open: true  # Enable interactive sessions
    command: /bin/bash
    environment:
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1  # Ensures Python output is sent straight to terminal without buffering
      - DATABASE_URL=postgresql://duylong:duylongpass@database:5432/duylongdb 
  database:
    image: postgres:17.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: duylong
      POSTGRES_DATABASE: duylongdb
      POSTGRES_PASSWORD: duylongpass
    ports:
      - "6000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
