  GNU nano 7.2                                                             /etc/nginx/nginx.conf                                                                      
    # 3. Hỗ trợ upload file lớn (Rất quan trọng cho MinIO)
    client_max_body_size 0;        # Không giới hạn kích thước file upload
    proxy_buffering off;           # Tắt buffering để hỗ trợ streaming file lớn
    proxy_request_buffering off;   # Quan trọng cho multipart upload của S3

    # 4. Timeout (Tăng lên nếu bạn thường xuyên upload file lớn)
    proxy_connect_timeout 300;
    proxy_read_timeout 300;
    proxy_send_timeout 300;

    # 5. Hỗ trợ WebSockets (Cho giao diện Console nếu cần)
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
                }       }
}


#mail {
#       # See sample authentication script at:
#       # http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#       # auth_http localhost/auth.php;
#       # pop3_capabilities "TOP" "USER";
#       # imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#       server {
#               listen     localhost:110;
#               protocol   pop3;
#               proxy      on;
#       }
#
#       server {
#               listen     localhost:143;
#               protocol   imap;
#               proxy      on;
#       }
#}

